using System;
using System.Collections.Generic;
using System.Reflection;
using System.Threading.Tasks;
using FairyGUI;
using UnityEngine;
using MiniGameTemplate.Utils;

namespace MiniGameTemplate.UI
{
    /// <summary>
    /// Central UI panel manager. Handles opening, closing, and tracking active panels.
    /// Uses Singleton pattern (framework-internal only).
    ///
    /// Panels are FairyGUI-exported GComponent subclasses that implement IUIPanel.
    /// UIManager uses the FairyGUI Extension mechanism (Binder + CreateObjectFromURL)
    /// to create panels, then manages their lifecycle.
    ///
    /// ALL panel opening is async — no synchronous Resources.Load path.
    /// </summary>
    public class UIManager : Singleton<UIManager>
    {
        private readonly Dictionary<Type, GComponent> _activePanels = new Dictionary<Type, GComponent>();
        private List<KeyValuePair<Type, GComponent>> _closeBuffer;

        // Modal overlay management
        private readonly Dictionary<Type, GGraph> _modalOverlays = new Dictionary<Type, GGraph>();

        // Cache: Type → (URL, PackageName) to avoid repeated reflection
        private readonly Dictionary<Type, PanelInfo> _panelInfoCache = new Dictionary<Type, PanelInfo>();

        // Guard against concurrent OpenPanelAsync calls for the same panel type
        private readonly HashSet<Type> _pendingOpens = new HashSet<Type>();

        // Binder registration tracking
        private static readonly Dictionary<string, Action> _binderRegistry = new Dictionary<string, Action>();
        private static readonly HashSet<string> _activatedBinders = new HashSet<string>();

        private struct PanelInfo
        {
            public string Url;
            public string PackageName;
        }

        [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.SubsystemRegistration)]
        private static void ResetStatics()
        {
            _binderRegistry.Clear();
            _activatedBinders.Clear();
        }

        /// <summary>
        /// Register a binder for a FairyGUI package. Call once at startup for each package.
        /// The binder will be activated (BindAll called) when the package is first used.
        /// Safe to call multiple times — duplicates are ignored.
        /// </summary>
        /// <param name="packageName">FairyGUI package name (e.g. "Common")</param>
        /// <param name="bindAction">The XXXBinder.BindAll method</param>
        public static void RegisterBinder(string packageName, Action bindAction)
        {
            if (!_binderRegistry.ContainsKey(packageName))
            {
                _binderRegistry[packageName] = bindAction;
                GameLog.Log($"[UIManager] Binder registered for package: {packageName}");
            }
        }

        /// <summary>
        /// Open a panel of type T asynchronously via YooAsset + FairyGUI Extension.
        /// Creates it if not already open, refreshes if already open.
        /// If loading fails, the panel is NOT registered — caller should catch the exception.
        ///
        /// T must be a FairyGUI-exported GComponent subclass that also implements IUIPanel.
        /// The class must have a public static const string URL field (generated by FairyGUI).
        /// </summary>
        public async Task<T> OpenPanelAsync<T>(object data = null) where T : GComponent, IUIPanel
        {
            var type = typeof(T);

            if (_activePanels.TryGetValue(type, out var existing))
            {
                ((IUIPanel)existing).OnRefresh(data);
                return (T)existing;
            }

            // Guard: prevent concurrent open calls for the same panel type
            if (!_pendingOpens.Add(type))
            {
                Debug.LogWarning($"[UIManager] OpenPanelAsync<{type.Name}> is already in progress. Ignoring duplicate call.");
                return null;
            }

            try
            {
                return await OpenPanelAsyncInternal<T>(type, data);
            }
            finally
            {
                _pendingOpens.Remove(type);
            }
        }

        private async Task<T> OpenPanelAsyncInternal<T>(Type type, object data) where T : GComponent, IUIPanel
        {

            // Get panel info (URL + PackageName) from cache or reflection
            var info = GetPanelInfo(type);

            // Activate binder for this package (if not yet activated)
            ActivateBinder(info.PackageName);

            // Load FairyGUI package via YooAsset
            await UIPackageLoader.AddPackageAsync(info.PackageName);

            // Create via FairyGUI Extension mechanism
            T panel;
            try
            {
                var obj = UIPackage.CreateObjectFromURL(info.Url);
                panel = obj as T;

                if (panel == null)
                {
                    // Extension didn't work — obj is a plain GComponent, not T
                    obj?.Dispose();
                    throw new InvalidOperationException(
                        $"UIPackage.CreateObjectFromURL returned {obj?.GetType().Name ?? "null"} instead of {type.Name}. " +
                        "Ensure the Binder is registered and BindAll() has been called.");
                }
            }
            catch (Exception ex)
            {
                UIPackageLoader.RemovePackage(info.PackageName);
                Debug.LogError($"[UIManager] Failed to create panel {type.Name}: {ex.Message}");
                throw;
            }

            // Setup layout
            panel.sortingOrder = ((IUIPanel)panel).PanelSortOrder;

            if (((IUIPanel)panel).IsFullScreen)
            {
                panel.MakeFullScreen();
                panel.AddRelation(GRoot.inst, RelationType.Size);
            }
            else
            {
                panel.Center();
                panel.AddRelation(GRoot.inst, RelationType.Center_Center);
                panel.AddRelation(GRoot.inst, RelationType.Middle_Middle);
            }

            // Modal overlay for dialogs
            if (panel is IModalDialog modalDialog)
            {
                CreateModalOverlay(type, ((IUIPanel)panel).PanelSortOrder, modalDialog.CloseOnClickOutside, panel);
            }

            GRoot.inst.AddChild(panel);

            _activePanels[type] = panel;
            ((IUIPanel)panel).OnOpen(data);

            return panel;
        }

        /// <summary>
        /// Close a panel of type T.
        /// </summary>
        public void ClosePanel<T>() where T : GComponent, IUIPanel
        {
            var type = typeof(T);
            if (!_activePanels.TryGetValue(type, out var panel)) return;

            _activePanels.Remove(type);
            CleanupPanel(type, panel);
        }

        /// <summary>
        /// Check if a panel type is currently open.
        /// </summary>
        public bool IsPanelOpen<T>() where T : GComponent, IUIPanel
        {
            return _activePanels.ContainsKey(typeof(T));
        }

        /// <summary>
        /// Get an active panel instance, or null if not open.
        /// </summary>
        public T GetPanel<T>() where T : GComponent, IUIPanel
        {
            _activePanels.TryGetValue(typeof(T), out var panel);
            return panel as T;
        }

        /// <summary>
        /// Close all open panels. Call on scene transition.
        /// Snapshot-then-clear pattern avoids InvalidOperationException
        /// if panel.OnClose() triggers further dictionary modifications.
        /// </summary>
        public void CloseAllPanels()
        {
            if (_activePanels.Count == 0) return;

            if (_closeBuffer == null)
                _closeBuffer = new List<KeyValuePair<Type, GComponent>>(_activePanels.Count);
            else
                _closeBuffer.Clear();

            foreach (var kvp in _activePanels)
                _closeBuffer.Add(kvp);

            _activePanels.Clear();

            for (int i = 0; i < _closeBuffer.Count; i++)
                CleanupPanel(_closeBuffer[i].Key, _closeBuffer[i].Value);

            _closeBuffer.Clear();
        }

        // ---- Private helpers ----

        private PanelInfo GetPanelInfo(Type type)
        {
            if (_panelInfoCache.TryGetValue(type, out var cached))
                return cached;

            // Read static const URL field via reflection (one-time cost per panel type)
            var urlField = type.GetField("URL", BindingFlags.Public | BindingFlags.Static | BindingFlags.FlattenHierarchy);
            if (urlField == null)
            {
                throw new InvalidOperationException(
                    $"[UIManager] Type {type.Name} does not have a public static URL field. " +
                    "Ensure FairyGUI code generation is enabled for this component.");
            }
            string url = (string)urlField.GetValue(null);

            // Read PanelPackageName: we need an instance property.
            // Since we can't call `new T()` safely (GComponent ctor has side effects),
            // we read the CreateInstance() method body to extract package name from it,
            // or we use a convention: the namespace name equals the package name.
            // Safest approach for IL2CPP/WebGL: use the namespace as package name.
            string packageName = type.Namespace;

            // Fallback: if namespace is null or empty, extract from URL pattern
            if (string.IsNullOrEmpty(packageName))
            {
                Debug.LogWarning($"[UIManager] Type {type.Name} has no namespace. " +
                    "Cannot determine package name. Ensure the panel class is in a namespace matching its FairyGUI package.");
                packageName = type.Name;
            }

            var info = new PanelInfo { Url = url, PackageName = packageName };
            _panelInfoCache[type] = info;
            return info;
        }

        private static void ActivateBinder(string packageName)
        {
            if (_activatedBinders.Contains(packageName))
                return;

            if (_binderRegistry.TryGetValue(packageName, out var bindAction))
            {
                bindAction();
                _activatedBinders.Add(packageName);
                GameLog.Log($"[UIManager] Activated binder for package: {packageName}");
            }
            else
            {
                Debug.LogWarning(
                    $"[UIManager] No binder registered for package '{packageName}'. " +
                    "Call UIManager.RegisterBinder() at startup. Panel creation may fail.");
            }
        }

        private void CleanupPanel(Type type, GComponent panel)
        {
            // Remove modal overlay if exists
            if (_modalOverlays.TryGetValue(type, out var overlay))
            {
                overlay.Dispose();
                _modalOverlays.Remove(type);
            }

            // Call lifecycle
            var uiPanel = panel as IUIPanel;
            uiPanel?.OnClose();

            // Get package name for ref-count release
            string packageName = uiPanel?.PanelPackageName;

            panel.Dispose();

            if (!string.IsNullOrEmpty(packageName))
                UIPackageLoader.RemovePackage(packageName);
        }

        private void CreateModalOverlay(Type panelType, int sortOrder, bool closeOnClickOutside, GComponent panel)
        {
            var overlay = new GGraph();
            overlay.SetSize(GRoot.inst.width, GRoot.inst.height);
            overlay.DrawRect(overlay.width, overlay.height, 0, Color.clear, new Color(0, 0, 0, 0.6f));
            overlay.AddRelation(GRoot.inst, RelationType.Size);
            overlay.sortingOrder = sortOrder - 1;
            GRoot.inst.AddChild(overlay);

            if (closeOnClickOutside)
            {
                // Capture panelType in closure for safe removal
                var capturedType = panelType;
                overlay.onClick.Add(() =>
                {
                    if (_activePanels.TryGetValue(capturedType, out var activePanel))
                    {
                        _activePanels.Remove(capturedType);
                        CleanupPanel(capturedType, activePanel);
                    }
                });
            }

            _modalOverlays[panelType] = overlay;
        }
    }
}
